<?php if ($_shippingRateGroups = $this->getShippingRates()): ?>
	<div id="order-shipping-method-choose" style="display:none">
	    <dl class="shipment-methods">
			<?php foreach ($_shippingRateGroups as $code => $_rates): ?>
		        <dt><strong><?php echo $this->getCarrierName($code) ?></strong></dt>
		        <dd>
		            <ul>
						<?php foreach ($_rates as $_rate): ?>
							<?php $_radioProperty = 'name="order[shipping_method]" type="radio" onclick="order.setShippingMethod(this.value)"' ?>
							<?php $_code = $_rate->getCode() ?>
			                <li>
								<?php if ($_rate->getErrorMessage()): ?>
									<ul class="messages">
										<li class="error-msg"><?php echo $_rate->getErrorMessage() ?></li>
									</ul>
								<?php else: ?>
									<?php $_checked = $this->isMethodActive($_code) ? 'checked="checked"' : '' ?>
									<input <?php echo $_radioProperty ?> value="<?php echo $_code ?>" id="s_method_<?php echo $_code ?>" <?php echo $_checked ?>/>
									<label class="normal" for="s_method_<?php echo $_code ?>">
										<?php echo $_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription() ?> -
										<strong>
											<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
											<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

											<?php echo $_excl; ?>
											<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
												(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
											<?php endif; ?>
										</strong>
									</label>
								<?php endif ?>
			                </li>
						<?php endforeach; ?>
		            </ul>
		        </dd>
			<?php endforeach; ?>
	    </dl>
	</div>
	<?php if ($_rate = $this->getActiveMethodRate()): ?>
		<div id="order-shipping-method-info">
			<strong><?php echo $this->getCarrierName($_rate->getCarrier()) ?></strong><br/>
			<?php echo $_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription() ?> -
			<strong>
				<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
				<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

				<?php echo $_excl; ?>
				<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
					(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
				<?php endif; ?>
			</strong>
			<!--input type="text" class="input-text" style="width:70px"/-->
			<br/>
			<a href="#" onclick="$('order-shipping-method-info').hide();
							$('order-shipping-method-choose').show();
							return false">
				<?php echo Mage::helper('sales')->__('Click to change shipping method') ?>
			</a>
		</div>
	<?php else: ?>
		<script type="text/javascript">$('order-shipping-method-choose').show();</script>
	<?php endif; ?>
<?php elseif ($this->getIsRateRequest()): ?>
	<strong><?php echo Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php else: ?>
	<div id="order-shipping-method-summary">
		<a href="#" onclick="order.loadShippingRates();
						return false">
			<?php echo Mage::helper('sales')->__('Get shipping methods and rates') ?>
		</a>
		<input type="hidden" name="order[has_shipping]" value="" class="required-entry">
	</div>
<?php endif; ?>
<div style="display:none;" id="shipping-method-overlay" class="overlay"><span><?php echo $this->__('Shipping method selection is not applicable') ?></span></div>
<script type="text/javascript">
				order.overlay('shipping-method-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
				order.overlay('address-shipping-overlay', <?php if ($this->getQuote()->isVirtual()): ?>false<?php else: ?>true<?php endif; ?>);
</script>

<?php
$blk = new Collinsharper_Purolator_Block_Checkout_Cart_Shipping();
$session = Mage::getModel('adminhtml/session_quote');
$quote = $session->getQuote();
$shippingaddress = $quote->getShippingAddress();
?>					
<!-- CollinsHarper.com purolator -->
<?php if ($_dd = $blk->testAddressAdmin($shippingaddress)): ?>
	<li><label for="corrected_address"><?php echo $this->helper('purolatormodule')->__('Invalid Address:') ?><span class="required">*</span></label><br />
		<?php if (is_array($_dd['addresses']) && count($_dd['addresses'])): ?>
			<?php foreach ($_dd['addresses'] as $add): ?>
				<a id="update-address" href="javascript:void(0);" onClick="javascript:updateAddress(<?php echo "'" . $add->City . "','" . $add->Province . "','" . $add->Country . "','" . $add->PostalCode . "'"; ?>);"><?php echo $add->City . ", " . $add->Province . ", " . $add->Country . ", " . $add->PostalCode; ?></a>
			<?php endforeach; ?><br />
		<?php endif; ?>
		<?php echo $_dd['description']; ?>
	</li>
<?php endif; ?>

<script type="text/javascript">
				Element.prototype.triggerEvent = function(eventName)
				{
					if (document.createEvent)
					{
						var evt = document.createEvent('HTMLEvents');
						evt.initEvent(eventName, true, true);

						return this.dispatchEvent(evt);
					}

					if (this.fireEvent)
						return this.fireEvent('on' + eventName);
				}

				function updateAddress(city, stateProv, country, postZip)
				{
					var billing_as_shipping = $('order-shipping_same_as_billing').checked;
					var regionStr = '<?php echo preg_replace('/\'/', '\\\'', $this->helper('directory')->getRegionJson()) ?>';
					regions = regionStr.evalJSON();



					if (billing_as_shipping) {
						$('order-billing_address_city').value = city;

						$('order-billing_address_country_id').value = country;

						$('order-billing_address_postcode').value = postZip;

						for (state in regions.US) {
							if (regions.US[state].code == stateProv) {
								$('order-billing_address_region_id').setAttribute('defaultValue', state);
							}

						}
						for (province in regions.CA) {
							if (regions.CA[province].code == stateProv) {
								$('order-billing_address_region_id').setAttribute('defaultValue', province);
								$('order-billing_address_region_id').value = province;
							}
						}

						//trigger the change event
						$('order-billing_address_region_id').triggerEvent('change');
						$('order-billing_address_postcode').triggerEvent('change');
						$('order-billing_address_country_id').triggerEvent('change');
						$('order-billing_address_city').triggerEvent('change');

					} else {
						$('order-shipping_address_city').value = city;

						$('order-shipping_address_country_id').value = country;

						$('order-shipping_address_postcode').value = postZip;

						for (state in regions.US) {
							if (regions.US[state].code == stateProv) {
								$('order-shipping_address_region_id').setAttribute('defaultValue', state);
							}

						}
						for (province in regions.CA) {
							if (regions.CA[province].code == stateProv) {
								$('order-shipping_address_region_id').setAttribute('defaultValue', province);
								$('order-shipping_address_region_id').value = province;
							}
						}

						//trigger the change event
						$('order-shipping_address_region_id').triggerEvent('change');
						$('order-shipping_address_postcode').triggerEvent('change');
						$('order-shipping_address_country_id').triggerEvent('change');
						$('order-shipping_address_city').triggerEvent('change');
					}

				}

</script>

